# Generated by Django 4.1.5 on 2023-01-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='empleado',
        ),
    ]
